# history
HISTFILE=~/.zsh_history
export HISTORY_IGNORE="(ls|cd|cd -|cd ..|z)"
HISTSIZE=10000
SAVEHIST=10000

setopt append_history
setopt share_history
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt extended_history

# prevent exiting with Ctrl-d
set -o ignoreeof

# 允许 >> 自动创建文件
setopt APPEND_CREATE

# 初始化 zsh 补全系统
autoload -Uz compinit
compinit

# ignore upper and lowercase when TAB completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# 使用 Emacs 编辑模式
bindkey -e

# Ctrl-W 按标点划分单词并向后删除
WORDCHARS=''
bindkey '^W' backward-kill-word

# ctrl+v 等价于 ctrl+x ctrl+e
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^V' edit-command-line

# plugins
{
  ZSH_PLUGINS_PATH="$HOME/.zsh/"

  # zsh-autosuggestions
  [[ -r "$ZSH_PLUGINS_PATH/zsh-autosuggestions/zsh-autosuggestions.zsh" ]] && source "$ZSH_PLUGINS_PATH/zsh-autosuggestions/zsh-autosuggestions.zsh"
  # # zsh-autocomplete
  # [[ -r "$ZSH_PLUGINS_PATH/zsh-autocomplete/zsh-autocomplete.plugin.zsh" ]] && source "$ZSH_PLUGINS_PATH/zsh-autocomplete/zsh-autocomplete.plugin.zsh"
  # zsh-syntax-highlighting
  [[ -r "$ZSH_PLUGINS_PATH/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]] && source "$ZSH_PLUGINS_PATH/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

  unset ZSH_PLUGINS_PATH
}
