#!/usr/bin/env bash

if [[ ! -s "$HOME/.nvm/nvm.sh" ]]; then
  return 0
fi

export NVM_DIR="$HOME/.nvm"
source "$NVM_DIR/nvm.sh"  # This loads nvm
[[ -s "$NVM_DIR/bash_completion" ]] && source "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
