#!/usr/bin/env bash

if ! command -v starship &> /dev/null; then
  return 1
fi

if [[ -n "$ZSH_VERSION" ]]; then
  eval "$(starship init zsh)"
elif [[ -n "$BASH_VERSION" ]]; then
  eval "$(starship init bash)"
fi
