#!/usr/bin/env bash

if ! command -v starship &> /dev/null; then
  return 0
fi

if [[ -n "$ZSH_VERSION" ]]; then
  eval "$(starship init zsh)"
elif [[ -n "$BASH_VERSION" ]]; then
  eval "$(starship init bash)"
fi

# 由 Starship 显示 Conda 环境, 关闭 Conda 自带的 PS1 前缀
[[ -n "$STARSHIP_SHELL" ]] && export CONDA_CHANGEPS1=false

