#!/usr/bin/env bash

#{{{> uv
# uv
if command -v uv &> /dev/null; then
  if [[ -n "$ZSH_VERSION" ]]; then
    eval "$(uv generate-shell-completion zsh)"
  elif [[ -n "$BASH_VERSION" ]]; then
    eval "$(uv generate-shell-completion bash)"
  fi
fi
# uvx
if command -v uvx &> /dev/null; then
  if [[ -n "$ZSH_VERSION" ]]; then
    eval "$(uvx --generate-shell-completion zsh)"
  elif [[ -n "$BASH_VERSION" ]]; then
    eval "$(uvx --generate-shell-completion bash)"
  fi
fi
#<}}}
