#!/usr/bin/env bash

#{{{> zoxide
if ! command -v zoxide &> /dev/null; then
  return 1
fi

if [[ -n "$ZSH_VERSION" ]]; then
  eval "$(zoxide init zsh)"
elif [[ -n "$BASH_VERSION" ]]; then
  eval "$(zoxide init bash)"
fi
#<}}}
