#!/usr/bin/env bash

function lssshcfg() {
  # Params:
  # - match_pattern

  local sed_match_pattern="um"
  local target_file="$HOME/.ssh/config"
  if [ $# -eq 1 ]; then
    sed_match_pattern=$1
  else
    echo "ERROR: Expect to match 2 params (IP and Host)."
    return 3
  fi

  local sed_match_value=$(cat $target_file | grep -v "# "| grep -E -A 3 -w "$sed_match_pattern\$")
  clprint "info" "Match Value:\n$sed_match_value"
}

