#!/usr/bin/env bash

to_upper() {
  echo "$@" | tr '[:lower:]' '[:upper:]'
}

to_lower() {
  echo "$@" | tr '[:upper:]' '[:lower:]'
}

if [[ -t 1 && -z "${NO_COLOR}" ]]; then
  # reset / style
  C_RESET="$(tput sgr0)"
  C_BOLD="$(tput bold)"
  C_UNDERLINE="$(tput smul)"
  # foreground
  FG_BLACK="$(tput setaf 0)"
  FG_RED="$(tput setaf 1)"
  FG_GREEN="$(tput setaf 2)"
  FG_YELLOW="$(tput setaf 3)"
  FG_BLUE="$(tput setaf 4)"
  FG_PURPLE="$(tput setaf 5)"
  FG_CYAN="$(tput setaf 6)"
  FG_WHITE="$(tput setaf 7)"
  # background
  BG_BLACK="$(tput setab 0)"
  BG_RED="$(tput setab 1)"
  BG_GREEN="$(tput setab 2)"
  BG_YELLOW="$(tput setab 3)"
  BG_BLUE="$(tput setab 4)"
  BG_PURPLE="$(tput setab 5)"
  BG_CYAN="$(tput setab 6)"
  BG_WHITE="$(tput setab 7)"
else
  # no color
  C_RESET=""
  C_BOLD=""
  C_UNDERLINE=""
  # foreground
  FG_BLACK=""
  FG_RED=""
  FG_GREEN=""
  FG_YELLOW=""
  FG_BLUE=""
  FG_PURPLE=""
  FG_CYAN=""
  FG_WHITE=""
  # background
  BG_BLACK=""
  BG_RED=""
  BG_GREEN=""
  BG_YELLOW=""
  BG_BLUE=""
  BG_PURPLE=""
  BG_CYAN=""
  BG_WHITE=""
fi

_cl_color() {
  case "$1" in
    finish)
      printf "%s" "${FG_GREEN}"
      ;;
    begin)
      printf "%s" "${FG_GREEN}${C_BOLD}"
      ;;
    opt)
      printf "%s" "${FG_YELLOW}"
      ;;
    error)
      printf "%s" "${FG_RED}${C_BOLD}"
      ;;
    warning)
      printf "%s" "${BG_YELLOW}${FG_BLACK}${C_BOLD}"
      ;;
    info)
      printf "%s" "${FG_CYAN}"
      ;;
    *)
      printf ""
      ;;
  esac
}

clprint() {
  mode="$(to_lower "$1")"
  shift
  color="$(_cl_color "$mode")"
  msg="${color}==> $*${C_RESET}"
  if [[ "$mode" == "opt" ]]; then
    printf "%b" "$msg"
  else
    printf "%b\n" "$msg"
  fi
}

bclprint() {
  mode="$(to_lower "$1")"
  shift
  color="$(_cl_color "$mode")"

  printf "%b\n" "$color"

  if [[ "$mode" == "opt" ]]; then
    echo "==> $1"
    shift
  else
    echo "==> $(to_upper "$mode") {{{"
  fi

  while [[ $# -ne 0 ]]; do
    echo "  $1"
    shift
  done

  if [[ "$mode" == "opt" ]]; then
    printf "%b" "$C_RESET"
  else
    echo "<=== }}}${C_RESET}"
    echo
  fi
}

opt_print() {
  opt="$1"
  val="$2"

  [[ -z "$opt" ]] && return

  if [[ ${#opt} -le 24 ]]; then
    printf "  %-24s%s\n" "$opt" "$val"
  else
    printf "  %-24s\n    %24s%s\n" "$opt" " " "$val"
  fi

  shift 2

  while [[ $# -ne 0 ]]; do
    printf "    %24s%s\n" " " "$1"
    shift
  done
}
